/**
 * This file was auto-generated by swagger-to-ts.
 * Do not make direct changes to the file.
 */

export interface definitions {
  expenses: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    receipt_number?: string;
    description?: string;
    date?: string;
    items?: string;
    total_cost?: string;
    user_id: string;
  };
}
